src/main/java/br/com/empresa/controller/LoginController.java
package br.com.empresa.controller;

import java.io.Serializable;

import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import javax.faces.context.FacesContext;
import javax.servlet.http.HttpSession;

import br.com.empresa.entidade.TipoUsuario;
import br.com.empresa.entidade.Usuario;
import br.com.empresa.rn.TipoUsuarioRN;
import br.com.empresa.rn.UsuarioRN;
import br.com.empresa.utils.Utils;

@ManagedBean(name = "loginController")
@ViewScoped
public class LoginController implements Serializable {

	private static final long serialVersionUID = 1L;

	private Usuario usuario = new Usuario();

	/*
	 * Construtor
	 */

	public LoginController() throws Exception {
		UsuarioRN usuarioRN = new UsuarioRN();
		Usuario usuario = usuarioRN.findByLogin(Utils.USUARIO_MASTER, Utils.USUARIO_MASTER);

		TipoUsuarioRN tipoUsuarioRN = new TipoUsuarioRN();
		TipoUsuario tipoUsuario = tipoUsuarioRN.carregarPorTipo(TipoUsuario.TIPO_MASTER);

		if (tipoUsuario == null) {
			tipoUsuario = new TipoUsuario();

			tipoUsuario.setValoresPadrao();
			tipoUsuario.setNomTipoUsuario("Master");
			tipoUsuario.setSglTipoUsuario(TipoUsuario.TIPO_MASTER);

			tipoUsuarioRN.inserir(tipoUsuario);
		}

		if (usuario == null) {
			usuario = new Usuario();

			usuario.setValoresPadrao();
			usuario.setNomUsuario(Utils.USUARIO_MASTER);
			usuario.setTxtSenha(Utils.USUARIO_MASTER);
			usuario.setTipoUsuario(tipoUsuario);
			usuario.setNumMatricula("000000");

			usuarioRN.inserir(usuario);
		}
	}

	/*
	 * Especificos
	 */

	public String doLogin() throws Exception {
		try {
			UsuarioRN usuarioRN = new UsuarioRN();

			setUsuario(usuarioRN.findByLogin(getUsuario().getNomUsuario(), getUsuario().getTxtSenha()));

			if (Utils.isNotNull(getUsuario())) {
				HttpSession session = (HttpSession) FacesContext.getCurrentInstance().getExternalContext().getSession(false);

				session.setAttribute("usuario", usuario);

				return "/restricted/forms/frm_index?faces-redirect=true";
			} else {
				throw new Exception("Favor verificar o nome de usuário e a senha.");
			}
		} catch (Exception e) {
			setUsuario(new Usuario());
			FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(e.getMessage()));
			FacesContext.getCurrentInstance().getExternalContext().getFlash().setKeepMessages(true);
			return "/frm_login?faces-redirect=true";
		}
	}

	public String logout() {
		FacesContext.getCurrentInstance().getExternalContext().invalidateSession();
		return "/frm_login?faces-redirect=true";
	}

	public boolean isUsuarioAdmin() {
		return getUsuarioLogado().getTipoUsuario().getSglTipoUsuario().equals(TipoUsuario.TIPO_ADMIN) || getUsuarioLogado().getTipoUsuario().getSglTipoUsuario().equals(TipoUsuario.TIPO_MASTER);
	}

	/*
	 * Getters e Setters
	 */

	public Usuario getUsuario() {
		return usuario;
	}

	public Usuario getUsuarioLogado() {
		HttpSession session = (HttpSession) FacesContext.getCurrentInstance().getExternalContext().getSession(false);
		return (Usuario) session.getAttribute("usuario");
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}
}

src/main/webapp/WEB-INF/templates/tpl_layout.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:h="http://xmlns.jcp.org/jsf/html" xmlns:f="http://xmlns.jcp.org/jsf/core" xmlns:ui="http://xmlns.jcp.org/jsf/facelets" xmlns:p="http://primefaces.org/ui">

<h:head>
	<f:facet name="first">
		<meta charset="UTF-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		<link rel="shortcut icon" href="#{request.contextPath}/resources/syscheck/images/favicon.ico" />
	</f:facet>

	<title>SysCheck</title>

	<h:outputStylesheet library="syscheck" name="css/custom.css" />
	<h:outputStylesheet library="syscheck" name="css/layout.css" />
	<h:outputStylesheet library="syscheck" name="css/components.css" />
	<h:outputStylesheet library="syscheck" name="css/sistema.css" />

	<h:outputScript target="body" library="primefaces" name="jquery/jquery.js" />
	<h:outputScript target="body" library="syscheck" name="js/app.js" />
	<h:outputScript target="body" library="syscheck" name="js/primeCalendar.js" />
</h:head>

<h:body id="blockArea" style="position: absolute!important;">
	<p:blockUI block="blockArea" widgetVar="block" />
	
	<p:ajaxStatus style="position: fixed; bottom: 0; right: 0; z-index: 99999;" onstart="PF('block').show()" onsuccess="PF('block').hide()">
		<f:facet name="start">
			<p:graphicImage library="syscheck" name="images/loading.gif" style="width: 50px; z-index:999999" />
		</f:facet>
		<f:facet name="complete">
			<h:outputText value="" />
		</f:facet>
	</p:ajaxStatus>

	<header class="aw-topbar" style="background-color: #1A1A1A; z-index: 99;">
		<a href="#" class="aw-toggle  js-toggle"><i class="fa fa-bars" /></a>
	</header>

	<div style="float: right; margin-right: 15px; font-size: 15px">
		<p>
			<strong>Bem vindo, #{loginController.usuarioLogado.nomUsuario}</strong>
		</p>
	</div>

	<aside class="aw-sidebar js-sidebar" style="z-index: 1; background-color: rgba(255, 255, 255, 0.6)">
		<ui:include src="tpl_menu.xhtml" />
	</aside>

	<section class="aw-content  js-content">
		<ui:insert name="content" />
	</section>

	<h:form>
		<p:confirmDialog global="true">
			<div align="center">
				<p:commandButton value="Não" type="button" styleClass="ui-confirmdialog-no" icon="fa fa-close" />
				<p:commandButton value="Sim" type="button" styleClass="ui-confirmdialog-yes" icon="fa fa-check" />
			</div>
		</p:confirmDialog>
	</h:form>

	<div class="footer" style="text-align: center">
		<footer>
			<p style="color: grey">&#169; SysCheck. 2017 - Todos os direitos reservados &#174;</p>
		</footer>
	</div>
</h:body>
<script type="text/javascript">
	window.onload = function() {
		document.getElementById('blockArea').style.position='absolute';
		document.getElementById('blockArea').style.height='100%';
	}
</script>
</html>

src/main/webapp/WEB-INF/templates/tpl_menu.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml" xmlns:ui="http://xmlns.jcp.org/jsf/facelets" xmlns:h="http://xmlns.jcp.org/jsf/html" xmlns:p="http://primefaces.org/ui">

	<h:form>
		<p:menu toggleable="true" style="border:none; padding-top: 0; padding-bottom: 0;">
			<p:submenu label="Cadastros" expanded="false" rendered="#{loginController.usuarioAdmin}">
				<p:menuitem value="Usuários" icon="fa fa-user-plus" outcome="/restricted/forms/frm_usuario.xhtml" />
				<p:menuitem value="Maquinas" icon="fa fa-user-plus" outcome="/restricted/forms/frm_equipamento.xhtml" />
				<p:menuitem value="Itens" icon="fa fa-user-plus" outcome="/restricted/forms/frm_item.xhtml" />
				<p:menuitem value="Fichas" icon="fa fa-user-plus" outcome="/restricted/forms/frm_check_list.xhtml" />
			</p:submenu>

			<p:submenu label="Check List" expanded="false">
				<p:menuitem value="Check List" icon="fa fa-user-plus" outcome="/restricted/forms/frm_check_list_resposta.xhtml" />
				<p:menuitem value="Check List Respondidos" icon="fa fa-user-plus" outcome="/restricted/forms/frm_check_list_respondidos.xhtml" />
			</p:submenu>

			<p:submenu label="Administração do Sistema" expanded="false">
				<p:menuitem value="Sair" icon="fa fa-power-off" action="#{loginController.logout()}" />
			</p:submenu>
		</p:menu>
	</h:form>
</ui:composition>